import { Ionicons } from "@expo/vector-icons";
import { useMemo, useState } from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { useGetCustomers, type CustomerWithHistory } from "@ody/api-client";
import { formatCurrency, formatRelativeTime, getInitials } from "@ody/shared";
import { CHANNEL_LABELS, STATUS_LABELS, type OrderChannel, type OrderStatus } from "@ody/types";
import { Badge, Card, DataList, DataListCell, DataListHeader, DataListRow, Drawer, EmptyState, Field, Skeleton, colors, fontSizes, fontWeights, radii, spacing } from "@ody/ui";
import { PageScaffold } from "@/components/PageScaffold";
import { QueryError } from "@/components/OperationalStates";

const statusTone = (status: string) => status === "completed" ? "success" : status === "cancelled" ? "danger" : status === "pending" ? "warning" : "primary";

export default function CrmPage() {
  const customers = useGetCustomers(); const [search, setSearch] = useState(""); const [selected, setSelected] = useState<CustomerWithHistory | null>(null);
  const filtered = useMemo(() => (customers.data ?? []).filter((customer) => `${customer.name} ${customer.email} ${customer.phone ?? ""}`.toLowerCase().includes(search.toLowerCase())), [customers.data, search]);
  const totalValue = customers.data?.reduce((sum, customer) => sum + customer.totalSpend, 0) ?? 0;
  return <PageScaffold eyebrow="Guest relationships" title="Customers" description="Understand guest frequency, value, and recent ordering activity.">
    <View style={styles.summary}><Card style={styles.summaryCard}><Text style={styles.summaryLabel}>Known customers</Text><Text style={styles.summaryValue}>{customers.data?.length ?? "—"}</Text></Card><Card style={styles.summaryCard}><Text style={styles.summaryLabel}>Customer value</Text><Text style={styles.summaryValue}>{formatCurrency(totalValue)}</Text></Card><Card style={styles.summaryCard}><Text style={styles.summaryLabel}>Returning guests</Text><Text style={styles.summaryValue}>{customers.data?.filter((customer) => customer.orderCount > 1).length ?? "—"}</Text></Card></View>
    <Card style={styles.searchCard}><Field label="Find a customer" placeholder="Search name, email, or phone" value={search} onChangeText={setSearch} /></Card>
    {customers.isPending ? <Card style={styles.loading}>{[1,2,3,4].map((item) => <View key={item} style={styles.loadingRow}><Skeleton width={40} height={40} /><Skeleton width="25%" /><Skeleton width={70} /><Skeleton width={90} /></View>)}</Card> : customers.isError ? <QueryError title="Customer records aren’t available" onRetry={() => customers.refetch()} /> : !filtered.length ? <Card><EmptyState icon="◎" title="No customers found" description={search ? "Try another name, email, or phone number." : "Customer profiles appear here after their first identified order."} actionLabel={search ? "Clear search" : undefined} onAction={search ? () => setSearch("") : undefined} /></Card> : <Card style={styles.tableCard}><DataList><DataListHeader columns={[{ label: "Customer", flex: 2 }, { label: "Orders", flex: .7 }, { label: "Total spend", flex: 1 }, { label: "Average", flex: 1 }, { label: "Last order", flex: 1 }]} />{filtered.map((customer) => <DataListRow key={customer.id} label={`Open ${customer.name}`} onPress={() => setSelected(customer)}><DataListCell flex={2}><View style={styles.customerCell}><View style={styles.avatar}><Text style={styles.avatarText}>{getInitials(customer.name)}</Text></View><View><Text style={styles.strong}>{customer.name}</Text><Text style={styles.muted}>{customer.email}</Text></View></View></DataListCell><DataListCell flex={.7}><Text style={styles.cell}>{customer.orderCount}</Text></DataListCell><DataListCell><Text style={styles.value}>{formatCurrency(customer.totalSpend)}</Text></DataListCell><DataListCell><Text style={styles.cell}>{formatCurrency(customer.averageOrder)}</Text></DataListCell><DataListCell><Text style={styles.cell}>{customer.lastOrderAt ? formatRelativeTime(customer.lastOrderAt) : "No orders"}</Text></DataListCell></DataListRow>)}</DataList></Card>}
    <CustomerDrawer customer={selected} onClose={() => setSelected(null)} />
  </PageScaffold>;
}

function CustomerDrawer({ customer, onClose }: { customer: CustomerWithHistory | null; onClose: () => void }) {
  return <Drawer open={Boolean(customer)} onClose={onClose} title={customer?.name ?? "Customer"} description="Guest profile and recent order activity">{customer && <ScrollView contentContainerStyle={styles.drawerContent}><View style={styles.profile}><View style={styles.profileAvatar}><Text style={styles.profileAvatarText}>{getInitials(customer.name)}</Text></View><View style={styles.profileCopy}><Text style={styles.profileName}>{customer.name}</Text><View style={styles.contact}><Ionicons name="mail-outline" size={15} color={colors.textMuted} /><Text style={styles.muted}>{customer.email}</Text></View>{customer.phone && <View style={styles.contact}><Ionicons name="call-outline" size={15} color={colors.textMuted} /><Text style={styles.muted}>{customer.phone}</Text></View>}</View></View><View style={styles.customerMetrics}><View style={styles.customerMetric}><Text style={styles.metricValue}>{customer.orderCount}</Text><Text style={styles.metricLabel}>Orders</Text></View><View style={styles.customerMetric}><Text style={styles.metricValue}>{formatCurrency(customer.totalSpend)}</Text><Text style={styles.metricLabel}>Spend</Text></View><View style={styles.customerMetric}><Text style={styles.metricValue}>{formatCurrency(customer.averageOrder)}</Text><Text style={styles.metricLabel}>Average</Text></View></View><View><Text style={styles.sectionTitle}>Recent orders</Text>{customer.recentOrders.length ? customer.recentOrders.map((order) => <View key={order.id} style={styles.orderRow}><View><Text style={styles.orderId}>{order.displayId}</Text><Text style={styles.muted}>{CHANNEL_LABELS[order.channel as OrderChannel]} · {formatRelativeTime(order.createdAt)}</Text></View><Badge tone={statusTone(order.status)}>{STATUS_LABELS[order.status as OrderStatus]}</Badge><Text style={styles.value}>{formatCurrency(order.total)}</Text></View>) : <EmptyState icon="⌁" title="No orders yet" description="Order history will appear here." />}</View></ScrollView>}</Drawer>;
}

const styles = StyleSheet.create({
  summary: { flexDirection: "row", flexWrap: "wrap", gap: spacing[4], marginBottom: spacing[4] }, summaryCard: { flex: 1, minWidth: 170, gap: spacing[1] }, summaryLabel: { color: colors.textMuted, fontSize: fontSizes.caption, fontWeight: fontWeights.bold }, summaryValue: { color: colors.text, fontSize: fontSizes.heading1, fontWeight: fontWeights.extraBold }, searchCard: { marginBottom: spacing[4] }, tableCard: { padding: 0, overflow: "hidden" }, loading: { gap: spacing[3] }, loadingRow: { minHeight: 55, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, customerCell: { flexDirection: "row", alignItems: "center", gap: spacing[3] }, avatar: { width: 38, height: 38, alignItems: "center", justifyContent: "center", borderRadius: radii.medium, backgroundColor: colors.primarySoft }, avatarText: { color: colors.primary, fontSize: fontSizes.micro, fontWeight: fontWeights.extraBold }, strong: { color: colors.text, fontSize: fontSizes.body, fontWeight: fontWeights.bold }, muted: { color: colors.textMuted, fontSize: fontSizes.micro, marginTop: 2 }, cell: { color: colors.text, fontSize: fontSizes.body }, value: { color: colors.text, fontSize: fontSizes.body, fontWeight: fontWeights.bold }, drawerContent: { gap: spacing[6], paddingBottom: spacing[8] }, profile: { flexDirection: "row", alignItems: "center", gap: spacing[4] }, profileAvatar: { width: 64, height: 64, alignItems: "center", justifyContent: "center", borderRadius: radii.large, backgroundColor: colors.primary }, profileAvatarText: { color: colors.textInverse, fontSize: fontSizes.heading3, fontWeight: fontWeights.extraBold }, profileCopy: { flex: 1 }, profileName: { color: colors.text, fontSize: fontSizes.heading2, fontWeight: fontWeights.extraBold }, contact: { flexDirection: "row", alignItems: "center", gap: spacing[2], marginTop: 4 }, customerMetrics: { flexDirection: "row", borderWidth: 1, borderColor: colors.border, borderRadius: radii.large, overflow: "hidden" }, customerMetric: { flex: 1, alignItems: "center", paddingVertical: spacing[4], borderRightWidth: 1, borderRightColor: colors.border }, metricValue: { color: colors.text, fontSize: fontSizes.heading3, fontWeight: fontWeights.extraBold }, metricLabel: { color: colors.textMuted, fontSize: fontSizes.micro, marginTop: 3 }, sectionTitle: { color: colors.text, fontSize: fontSizes.heading3, fontWeight: fontWeights.extraBold, marginBottom: spacing[3] }, orderRow: { minHeight: 68, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing[3], borderBottomWidth: 1, borderBottomColor: colors.border }, orderId: { color: colors.primary, fontSize: fontSizes.body, fontWeight: fontWeights.bold },
});
