import { Ionicons } from "@expo/vector-icons";
import { useEffect, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import type { CreateMenuItem, MenuItem, UpdateMenuItem } from "@ody/api-client";
import { formatCurrency } from "@ody/shared";
import { Badge, Button, Card, Drawer, Dropdown, EmptyState, Field, InlineMessage, Skeleton, Toast, Toggle, colors, fontSizes, fontWeights, radii, spacing } from "@ody/ui";
import { PageScaffold } from "@/components/PageScaffold";
import { QueryError, SectionHeading } from "@/components/OperationalStates";
import { useMenuOperations } from "@/hooks/useMenuOperations";

export default function MenuPage() {
  const operations = useMenuOperations();
  const totalItems = operations.menu.data?.reduce((sum, category) => sum + category.items.length, 0) ?? 0;
  return <PageScaffold eyebrow="Catalogue" title="Menu" description="Keep dishes, prices, preparation times, and availability accurate." action={<View style={styles.headerActions}><Button variant="secondary" onPress={operations.openCategory}>+ Category</Button><Button onPress={operations.openCreate}>+ Menu item</Button></View>}>
    <View style={styles.summary}><Card style={styles.summaryCard}><Text style={styles.summaryLabel}>Menu items</Text><Text style={styles.summaryValue}>{totalItems}</Text></Card><Card style={styles.summaryCard}><Text style={styles.summaryLabel}>Categories</Text><Text style={styles.summaryValue}>{operations.menu.data?.length ?? 0}</Text></Card><Card style={styles.summaryCard}><Text style={styles.summaryLabel}>Unavailable</Text><Text style={styles.summaryValue}>{operations.menu.data?.flatMap((category) => category.items).filter((item) => !item.isAvailable).length ?? 0}</Text></Card></View>
    {operations.menu.isPending ? <View style={styles.loading}><Skeleton height={160} /><Skeleton height={160} /></View> : operations.menu.isError ? <QueryError title="The menu couldn’t be loaded" onRetry={() => operations.menu.refetch()} /> : !operations.menu.data?.length ? <Card><EmptyState title="Build your first menu" description="Add a category, then create dishes that guests can order." actionLabel="Add category" onAction={operations.openCategory} /></Card> : operations.menu.data.map((category) => <View key={category.id}><SectionHeading title={category.name} description={category.description ?? `${category.items.length} menu items`} /><Card style={styles.categoryCard}>{category.items.length ? category.items.map((item, index) => <MenuRow key={item.id} item={item} last={index === category.items.length - 1} onEdit={() => operations.openEdit(item)} onToggle={() => operations.toggleAvailability(item)} />) : <EmptyState icon="＋" title="This category is empty" description="Add an item to make it visible to the kitchen." actionLabel="Add menu item" onAction={operations.openCreate} />}</Card></View>)}
    <ItemEditor open={operations.editorOpen} item={operations.editingItem} categories={operations.menu.data?.map((category) => ({ label: category.name, value: category.id })) ?? []} onClose={operations.closeEditor} onSave={operations.saveItem} pending={operations.pending} error={operations.error} />
    <CategoryEditor open={operations.categoryOpen} onClose={operations.closeCategory} onSave={operations.saveCategory} pending={operations.categoryPending} error={operations.categoryError} />
    <Toast message={operations.notice} />
  </PageScaffold>;
}

function MenuRow({ item, last, onEdit, onToggle }: { item: MenuItem; last: boolean; onEdit: () => void; onToggle: () => void }) {
  return <View style={[styles.menuRow, !last && styles.rowBorder]}><View style={[styles.dishIcon, !item.isAvailable && styles.dishIconMuted]}><Ionicons name="restaurant-outline" size={20} color={item.isAvailable ? colors.primary : colors.textSubtle} /></View><View style={styles.itemCopy}><View style={styles.itemTitleRow}><Text style={styles.itemName}>{item.name}</Text><Badge tone={item.isAvailable ? "success" : "neutral"} dot>{item.isAvailable ? "Available" : "Unavailable"}</Badge></View><Text style={styles.description} numberOfLines={1}>{item.description}</Text><Text style={styles.prep}>{item.prepMinutes} min prep</Text></View><Text style={styles.price}>{formatCurrency(item.price)}</Text><Toggle label="" value={item.isAvailable} onChange={onToggle} /><Pressable accessibilityRole="button" accessibilityLabel={`Edit ${item.name}`} onPress={onEdit} style={styles.editButton}><Ionicons name="create-outline" size={19} color={colors.textMuted} /></Pressable></View>;
}

function ItemEditor({ open, item, categories, onClose, onSave, pending, error }: { open: boolean; item: MenuItem | null; categories: { label: string; value: number }[]; onClose: () => void; onSave: (data: CreateMenuItem | UpdateMenuItem) => void; pending: boolean; error: unknown }) {
  const [categoryId, setCategoryId] = useState<number | undefined>(); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [price, setPrice] = useState(""); const [prepMinutes, setPrepMinutes] = useState("10"); const [available, setAvailable] = useState(true);
  useEffect(() => { setCategoryId(item?.categoryId ?? categories[0]?.value); setName(item?.name ?? ""); setDescription(item?.description ?? ""); setPrice(item ? String(item.price / 100) : ""); setPrepMinutes(String(item?.prepMinutes ?? 10)); setAvailable(item?.isAvailable ?? true); }, [item, open, categories.length]);
  const save = () => { const cents = Math.round(Number(price) * 100); if (categoryId && name.trim().length >= 2 && cents > 0) onSave({ categoryId, name: name.trim(), description: description.trim(), price: cents, prepMinutes: Number(prepMinutes), isAvailable: available }); };
  return <Drawer open={open} onClose={onClose} title={item ? "Edit menu item" : "Add menu item"} description="Changes are reflected in ordering immediately."><ScrollView contentContainerStyle={styles.form}><Dropdown label="Category" value={categoryId} options={categories} onChange={setCategoryId} /><Field label="Item name" required value={name} onChangeText={setName} placeholder="e.g. Truffle rigatoni" /><Field label="Description" value={description} onChangeText={setDescription} placeholder="Ingredients and preparation" multiline /><View style={styles.fieldRow}><View style={styles.fieldHalf}><Field label="Price (€)" required value={price} onChangeText={setPrice} keyboardType="decimal-pad" placeholder="18.50" /></View><View style={styles.fieldHalf}><Field label="Prep time (min)" required value={prepMinutes} onChangeText={setPrepMinutes} keyboardType="number-pad" /></View></View><Toggle label="Available to order" description="Unavailable dishes cannot be added to new orders." value={available} onChange={setAvailable} />{Boolean(error) && <InlineMessage tone="error" title="Item couldn’t be saved">Review the fields and try again.</InlineMessage>}<Button loading={pending} disabled={!categoryId || name.trim().length < 2 || Number(price) <= 0} onPress={save}>{item ? "Save changes" : "Add to menu"}</Button></ScrollView></Drawer>;
}

function CategoryEditor({ open, onClose, onSave, pending, error }: { open: boolean; onClose: () => void; onSave: (data: { name: string; description?: string }) => void; pending: boolean; error: unknown }) {
  const [name, setName] = useState(""); const [description, setDescription] = useState("");
  return <Drawer open={open} onClose={onClose} title="Add category" description="Use clear categories to keep menu management fast."><View style={styles.form}><Field label="Category name" required value={name} onChangeText={setName} placeholder="e.g. Small plates" /><Field label="Description" value={description} onChangeText={setDescription} multiline />{Boolean(error) && <InlineMessage tone="error" title="Category couldn’t be added">A category with this name may already exist.</InlineMessage>}<Button loading={pending} disabled={name.trim().length < 2} onPress={() => onSave({ name: name.trim(), description: description.trim() || undefined })}>Add category</Button></View></Drawer>;
}

const styles = StyleSheet.create({
  headerActions: { flexDirection: "row", gap: spacing[2] }, summary: { flexDirection: "row", flexWrap: "wrap", gap: spacing[4], marginBottom: spacing[2] }, summaryCard: { flex: 1, minWidth: 150, gap: spacing[1] }, summaryLabel: { color: colors.textMuted, fontSize: fontSizes.caption, fontWeight: fontWeights.bold }, summaryValue: { color: colors.text, fontSize: fontSizes.heading1, fontWeight: fontWeights.extraBold }, loading: { gap: spacing[4] }, categoryCard: { paddingVertical: 0 }, menuRow: { minHeight: 92, flexDirection: "row", alignItems: "center", gap: spacing[4] }, rowBorder: { borderBottomWidth: 1, borderBottomColor: colors.border }, dishIcon: { width: 48, height: 48, alignItems: "center", justifyContent: "center", borderRadius: radii.medium, backgroundColor: colors.primarySoft }, dishIconMuted: { backgroundColor: colors.surfaceMuted }, itemCopy: { flex: 1, minWidth: 150 }, itemTitleRow: { flexDirection: "row", alignItems: "center", gap: spacing[2] }, itemName: { color: colors.text, fontSize: fontSizes.bodyLarge, fontWeight: fontWeights.bold }, description: { color: colors.textMuted, fontSize: fontSizes.caption, marginTop: 3 }, prep: { color: colors.textSubtle, fontSize: fontSizes.micro, marginTop: 4 }, price: { minWidth: 74, color: colors.text, fontSize: fontSizes.bodyLarge, fontWeight: fontWeights.extraBold }, editButton: { width: 40, height: 40, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: colors.border, borderRadius: radii.medium }, form: { gap: spacing[5], paddingBottom: spacing[8] }, fieldRow: { flexDirection: "row", gap: spacing[3] }, fieldHalf: { flex: 1 },
});
