import { useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import { Badge, Button, Card, Dialog, Divider, Dropdown, EmptyState, Field, InlineMessage, SegmentedSelect, Skeleton, Toggle, colors, fontSizes, fontWeights, palette, radii, shadows, spacing } from "@ody/ui";
import { PageScaffold } from "@/components/PageScaffold";

const swatches = [
  ["Primary", colors.primary], ["Accent", colors.accent], ["Canvas", colors.background], ["Surface", colors.surface], ["Text", colors.text], ["Muted", colors.textMuted], ["Success", colors.success], ["Warning", colors.warning], ["Danger", colors.danger], ["Info", colors.info],
] as const;

export default function UiLibraryPage() {
  const [segment, setSegment] = useState("pickup"); const [dropdown, setDropdown] = useState("main"); const [toggle, setToggle] = useState(true); const [dialog, setDialog] = useState(false);
  return <PageScaffold eyebrow="Design system" title="UI Library" description="A living reference for Ody’s tokens, reusable components, and product states.">
    <LibrarySection number="01" title="Color tokens" description="Warm neutral foundations with focused operational accents."><View style={styles.swatches}>{swatches.map(([name, color]) => <View key={name} style={styles.swatch}><View style={[styles.color, { backgroundColor: color }]} /><Text style={styles.swatchName}>{name}</Text><Text style={styles.code}>{color}</Text></View>)}</View></LibrarySection>

    <LibrarySection number="02" title="Typography" description="A compact scale designed for dense operational information."><Card><TypeRow label="Display / 36" size={fontSizes.display} weight={fontWeights.extraBold}>Restaurant overview</TypeRow><Divider /><TypeRow label="Heading 1 / 28" size={fontSizes.heading1} weight={fontWeights.extraBold}>Good afternoon, Dina</TypeRow><Divider /><TypeRow label="Heading 2 / 22" size={fontSizes.heading2} weight={fontWeights.bold}>Recent orders</TypeRow><Divider /><TypeRow label="Body / 14" size={fontSizes.body} weight={fontWeights.regular}>Keep your team moving with clear, current information.</TypeRow><Divider /><TypeRow label="Caption / 12" size={fontSizes.caption} weight={fontWeights.semibold}>UPDATED 2 MINUTES AGO</TypeRow></Card></LibrarySection>

    <LibrarySection number="03" title="Spacing & surfaces" description="A four-point rhythm, soft radii, and restrained elevation."><View style={styles.twoColumns}><Card title="Spacing scale" style={styles.flexCard}><View style={styles.spacingList}>{Object.entries(spacing).slice(1, 11).map(([token, value]) => <View key={token} style={styles.spacingRow}><Text style={styles.tokenLabel}>space.{token}</Text><View style={[styles.spacingBar, { width: value }]} /><Text style={styles.code}>{value}px</Text></View>)}</View></Card><View style={styles.flexCard}><Card title="Base surface" description="Cards and grouped information" style={styles.surfaceDemo}><Text style={styles.body}>Border, radius, and card elevation.</Text></Card><View style={[styles.darkSurface, shadows.overlay]}><Badge tone="success" dot>Live</Badge><Text style={styles.darkTitle}>Strong surface</Text><Text style={styles.darkBody}>Used sparingly for emphasis and overlays.</Text></View></View></View></LibrarySection>

    <LibrarySection number="04" title="Components" description="Reusable controls with hover, focus, active, loading, and disabled states."><Card title="Buttons"><View style={styles.row}><Button>Primary action</Button><Button variant="secondary">Secondary</Button><Button variant="ghost">Ghost</Button><Button variant="danger">Destructive</Button><Button loading>Saving</Button><Button disabled>Disabled</Button></View></Card><View style={styles.twoColumns}><Card title="Form controls" style={styles.flexCard}><View style={styles.form}><Field label="Restaurant name" value="Atelier Ody" /><Field label="Email" value="not-an-email" error="Enter a valid email address" /><Dropdown label="Category" value={dropdown} onChange={setDropdown} options={[{ label: "Small plates", value: "small" }, { label: "Mains", value: "main" }, { label: "Drinks", value: "drinks" }]} /><SegmentedSelect label="Order type" value={segment} onChange={setSegment} options={[{ label: "Pickup", value: "pickup" }, { label: "Delivery", value: "delivery" }]} /><Toggle label="Online ordering" description="Accept new orders" value={toggle} onChange={setToggle} /></View></Card><Card title="Status & feedback" style={styles.flexCard}><View style={styles.form}><View style={styles.row}><Badge>Neutral</Badge><Badge tone="primary" dot>Preparing</Badge><Badge tone="success" dot>Ready</Badge><Badge tone="warning" dot>New</Badge><Badge tone="danger" dot>Cancelled</Badge></View><InlineMessage tone="success" title="Changes saved">The menu is now up to date.</InlineMessage><InlineMessage tone="warning" title="Service ends soon">Ordering closes in 30 minutes.</InlineMessage><InlineMessage tone="error" title="Couldn’t create order">One item is no longer available.</InlineMessage><Button variant="secondary" onPress={() => setDialog(true)}>Open dialog</Button></View></Card></View></LibrarySection>

    <LibrarySection number="05" title="Product states" description="Every data view has a deliberate loading, empty, success, warning, and error pattern."><View style={styles.stateGrid}><Card title="Loading" style={styles.stateCard}><View style={styles.form}><Skeleton width="40%" /><Skeleton height={30} /><Skeleton width="72%" /></View></Card><Card title="Empty" style={styles.stateCard}><EmptyState icon="⌁" title="No orders yet" description="New orders will appear here." /></Card><Card title="Success" style={styles.stateCard}><InlineMessage tone="success" title="Ready for pickup">Order OD-1050 is packed.</InlineMessage></Card><Card title="Warning" style={styles.stateCard}><InlineMessage tone="warning" title="Low availability">Two dishes are unavailable.</InlineMessage></Card><Card title="Error" style={styles.stateCard}><InlineMessage tone="error" title="Connection lost">Retry when the API is available.</InlineMessage></Card></View></LibrarySection>

    <Dialog open={dialog} onClose={() => setDialog(false)} title="Confirm service change" description="Dialogs keep high-impact actions focused and deliberate."><View style={styles.dialogActions}><Button variant="secondary" onPress={() => setDialog(false)}>Cancel</Button><Button onPress={() => setDialog(false)}>Confirm</Button></View></Dialog>
  </PageScaffold>;
}

function LibrarySection({ number, title, description, children }: React.PropsWithChildren<{ number: string; title: string; description: string }>) {
  return <View style={styles.section}><View style={styles.sectionHeading}><Text style={styles.number}>{number}</Text><View><Text style={styles.title}>{title}</Text><Text style={styles.description}>{description}</Text></View></View>{children}</View>;
}

function TypeRow({ label, size, weight, children }: React.PropsWithChildren<{ label: string; size: number; weight: typeof fontWeights[keyof typeof fontWeights] }>) {
  return <View style={styles.typeRow}><Text style={styles.typeLabel}>{label}</Text><Text style={{ flex: 1, color: colors.text, fontSize: size, lineHeight: Math.round(size * 1.25), fontWeight: weight }}>{children}</Text></View>;
}

const styles = StyleSheet.create({
  section: { marginBottom: spacing[12] }, sectionHeading: { flexDirection: "row", alignItems: "flex-start", gap: spacing[3], marginBottom: spacing[5] }, number: { color: colors.primary, fontSize: fontSizes.micro, fontWeight: fontWeights.extraBold, marginTop: 5 }, title: { color: colors.text, fontSize: fontSizes.heading2, fontWeight: fontWeights.extraBold }, description: { color: colors.textMuted, fontSize: fontSizes.caption, marginTop: spacing[1] }, swatches: { flexDirection: "row", flexWrap: "wrap", gap: spacing[3] }, swatch: { width: 116, padding: spacing[2], borderWidth: 1, borderColor: colors.border, borderRadius: radii.medium, backgroundColor: colors.surface }, color: { height: 70, borderRadius: radii.small, borderWidth: 1, borderColor: "rgba(0,0,0,.06)" }, swatchName: { color: colors.text, fontSize: fontSizes.caption, fontWeight: fontWeights.bold, marginTop: spacing[2] }, code: { color: colors.textSubtle, fontSize: fontSizes.micro, fontFamily: "monospace", marginTop: 2 }, typeRow: { flexDirection: "row", alignItems: "baseline", gap: spacing[6] }, typeLabel: { width: 110, color: colors.textSubtle, fontSize: fontSizes.micro, fontFamily: "monospace" }, twoColumns: { flexDirection: "row", flexWrap: "wrap", alignItems: "flex-start", gap: spacing[4] }, flexCard: { flex: 1, minWidth: 310 }, spacingList: { gap: spacing[3] }, spacingRow: { flexDirection: "row", alignItems: "center", gap: spacing[3] }, tokenLabel: { width: 70, color: colors.textMuted, fontSize: fontSizes.caption }, spacingBar: { height: 12, borderRadius: radii.small, backgroundColor: colors.primary }, surfaceDemo: { marginBottom: spacing[4] }, body: { color: colors.textMuted, fontSize: fontSizes.body }, darkSurface: { padding: spacing[5], borderRadius: radii.large, backgroundColor: colors.surfaceStrong }, darkTitle: { color: colors.textInverse, fontSize: fontSizes.heading3, fontWeight: fontWeights.extraBold, marginTop: spacing[4] }, darkBody: { color: palette.stone400, fontSize: fontSizes.caption, marginTop: spacing[1] }, row: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: spacing[2] }, form: { gap: spacing[4] }, stateGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing[4] }, stateCard: { flex: 1, minWidth: 240 }, dialogActions: { flexDirection: "row", justifyContent: "flex-end", gap: spacing[2] },
});
